services:
  fastapi-chat:
    build: .
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    working_dir: /app
    volumes:
      - ./data:/app/data  # persist DB outside container
      - .:/app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: on-failure
